version: '3'

services:
  mindwendel:
    container_name: mindwendel
    build:
      context: .
    environment:
      DATABASE_USER: postgres
      DATABASE_USER_PASSWORD: postgres
      DATABASE_NAME: mindwendel
      DATABASE_PORT: 5432
      DATABASE_HOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db
    # Mount the app folder to increase development speed.
    volumes:
      - .:/app
    # In case you want to use the included .env file to provide the credentials.
    # env_file:
    #  - .env
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
